server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: producer_route
          uri: lb://producerService
          predicates:
            - Path=/api/producer/**
          filters:
            - StripPrefix=1

        - id: consumer_route
          uri: lb://consumerService
          predicates:
            - Path=/api/consumer/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
